stages:
  get_data:
    cmd: python src/prepare.py
    deps:
    - src/prepare.py
    - params.yaml
    params:
    - date
    outs:
    - data/raw.csv
  preprocess:
    cmd: python src/preprocess.py
    deps:
    - src/preprocess.py
    - data/raw.csv
    - params.yaml
    outs:
    - data/preprocessed.csv
